spring:
  application:
    name: transformer
  datasource:
    url: jdbc:mysql://localhost:3306/openalex?useSSL=false&serverTimezone=UTC
    username: root
    password: "1234"
    hikari:
      maximum-pool-size: 10
  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: 123456

